### ISSUE TITLE
XP Bottle Dupe

### ISSUE THREAD

**Issue by loganfx** [kikipunk/XpStorage-DataPack#1]

**Comment by loganfx** [comment]
In Minecraft 1.13.2 If you take any filled bottle with experience less than 1408/1408 and put it in the second slot of "XP Hopper" It will dupe into the second slot.
![xpdupe1](https://user-images.githubusercontent.com/8317287/48455028-a3d44980-e787-11e8-871c-801939e84196.png)
![xpdupe2](https://user-images.githubusercontent.com/8317287/48455029-a3d44980-e787-11e8-873b-ee361d1cb2dc.gif)

To make the matter worse it can be sucked out with a hopper and pumped into a chest.
![xpdupe3](https://user-images.githubusercontent.com/8317287/48455030-a3d44980-e787-11e8-98d4-7203e69b1270.png)
![xpdupe4](https://user-images.githubusercontent.com/8317287/48455031-a3d44980-e787-11e8-8f0b-a3200ba7a1d5.gif)

**Comment by kikipunk** [comment]
Thank's you have the 1.3 version of xpstorage?

**Comment by kikipunk** [comment]
Fix in version 1.6
